# NAME: POOJAN SHETH


# Python Assignment 5

## Numpy

### 1. Write a Python program to print the NumPy version in your system.


In [4]:
import numpy as np
np.__version__

'1.22.3'

### 2. Write a Python program to convert a list of numeric value into a one- dimensional NumPy array

In [5]:
lst=[25,60,21,30,80,50]
arr=np.array(lst)
print(arr.size,type(arr))
arr

6 <class 'numpy.ndarray'>


array([25, 60, 21, 30, 80, 50])

### 3. Write a Python program to create an array with values ranging from 12 to 38.

In [19]:
np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

### 4. Write a Python program to convert a list and tuple into arrays.

In [12]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr1=np.array(lst)
tpl=('p','y','t','h','o','n')
arr2=np.array(tpl)
arr1,arr2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array(['p', 'y', 't', 'h', 'o', 'n'], dtype='<U1'))

### 5. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [18]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(lst)
print('Number of elements of an array are ',arr.size)
print('Length of one array element in bytes is ',arr.itemsize)
print('Total bytes consumed by the elements are ',arr.nbytes)

Number of elements of an array are  10
Length of one array element in bytes is  4
Total bytes consumed by the elements are  40


### 6. Write a Python program compare two arrays using numpy.

In [26]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr1=np.array(lst)
tpl=(11,12,13,14,15,16,17,18,19,20)
arr2=np.array(tpl)
print(np.greater(arr1,arr2))
print(np.greater_equal(arr1,arr2))
print(np.less(arr1,arr2))
print(np.less_equal(arr1,arr2))


[False False False False False False False False False False]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]


### 7. Write a Python program to get the number of nonzero elements in an array.

In [31]:
np.count_nonzero(np.arange(0,11))

10

### 8. Write a Python program to check whether the numpy array is empty or not.

In [37]:
lst=[]
arr=np.array(lst)
if np.size(arr)>0:
    print('Array is not empty')
elif np.size(arr)==0:
    print('Array is empty')

Array is empty


### 9. Write a Python program to get the powers of an array values element-wise.

In [39]:
arr=np.arange(10)
power=np.power(arr,2)
power

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

### 10. Write a Python program to stack two arrays: 1) row-wise 2) column-wise
- Arr1 = np.linspace(1,20,50)
- Arr2 = np.linspace(21,40,50)


In [42]:
arr1 = np.linspace(1,20,50)
arr2 = np.linspace(21,40,50)
np.row_stack((arr1,arr2))

array([[ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
         2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
         4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
         6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
         8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
        10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
        12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
        14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
        16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
        18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ],
       [21.        , 21.3877551 , 21.7755102 , 22.16326531, 22.55102041,
        22.93877551, 23.32653061, 23.71428571, 24.10204082, 24.48979592,
        24.87755102, 25.26530612, 25.65306122, 26.04081633, 26.42857143,
        26.81632653, 27.20408163, 27.59183673, 27.

In [43]:
arr1 = np.linspace(1,20,50)
arr2 = np.linspace(21,40,50)
np.column_stack((arr1,arr2))

array([[ 1.        , 21.        ],
       [ 1.3877551 , 21.3877551 ],
       [ 1.7755102 , 21.7755102 ],
       [ 2.16326531, 22.16326531],
       [ 2.55102041, 22.55102041],
       [ 2.93877551, 22.93877551],
       [ 3.32653061, 23.32653061],
       [ 3.71428571, 23.71428571],
       [ 4.10204082, 24.10204082],
       [ 4.48979592, 24.48979592],
       [ 4.87755102, 24.87755102],
       [ 5.26530612, 25.26530612],
       [ 5.65306122, 25.65306122],
       [ 6.04081633, 26.04081633],
       [ 6.42857143, 26.42857143],
       [ 6.81632653, 26.81632653],
       [ 7.20408163, 27.20408163],
       [ 7.59183673, 27.59183673],
       [ 7.97959184, 27.97959184],
       [ 8.36734694, 28.36734694],
       [ 8.75510204, 28.75510204],
       [ 9.14285714, 29.14285714],
       [ 9.53061224, 29.53061224],
       [ 9.91836735, 29.91836735],
       [10.30612245, 30.30612245],
       [10.69387755, 30.69387755],
       [11.08163265, 31.08163265],
       [11.46938776, 31.46938776],
       [11.85714286,

## Pandas (Series and DataFrame)

### 1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
import pandas as pd

In [4]:
s=pd.Series(range(0,31,2))
s

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
11    22
12    24
13    26
14    28
15    30
dtype: int64

### 2. Write a Python program to convert a Panda module Series to Python list and its type.

In [11]:
s=pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s)
print(type(s))
s1=s.to_list()
print(s1)
print(type(s1))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
<class 'pandas.core.series.Series'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


### 3. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [19]:
s1=pd.Series(range(1,51,10))
s2=pd.Series(range(41,91,10))


In [20]:
s1+s2

0     42
1     62
2     82
3    102
4    122
dtype: int64

In [21]:
s1-s2

0   -40
1   -40
2   -40
3   -40
4   -40
dtype: int64

In [22]:
s1*s2

0      41
1     561
2    1281
3    2201
4    3321
dtype: int64

In [23]:
s1/s2

0    0.024390
1    0.215686
2    0.344262
3    0.436620
4    0.506173
dtype: float64

### 4. Write a Python program to compare the elements of the two Pandas Series.

In [24]:
s1=pd.Series(range(1,51,10))
s2=pd.Series(range(41,91,10))

In [29]:
s1>=s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [30]:
s1<=s2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [27]:
s1==s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [28]:
s1!=s2

0    True
1    True
2    True
3    True
4    True
dtype: bool

### 5. Write a Python program to display the following data column wise.
exam_data = {'name': ['Anastasia', 'Dima','Katherine', 'James', 'Emily', 'Michael', 'Matthew','Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5,np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1,3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no','yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h','i', 'j']

In [41]:
exam_data = pd.DataFrame({'name': ['Anastasia', 'Dima','Katherine', 'James', 'Emily', 'Michael', 'Matthew','Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5,np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1,3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no','yes', 'yes', 'no', 'no', 'yes']})
exam_data

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

### 6. Write a Python program to create and display a Data Frame from a specified dictionary data which has the index labels.

In [5]:
exam_data1 = pd.DataFrame({'name': ['Anastasia', 'Dima','Katherine', 'James', 'Emily', 'Michael', 'Matthew','Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5,np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1,3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no','yes', 'yes', 'no', 'no', 'yes']},index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h','i', 'j'])
exam_data1

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

### 7. Write a Python program to select the specified columns and rows from a given Data Frame.

In [9]:
df=exam_data1.loc['d':'g','score':'qualify']
df

score  attempts qualify
d    NaN         3      no
e    9.0         2      no
f   20.0         3     yes
g   14.5         1     yes

### 8. Write a Python program to select the rows the score is between 15 and 20 (inclusive).

In [54]:
exam_data1[exam_data1.score.between(15,20)]

name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

### 9. Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [56]:
exam_data1[(exam_data1.attempts<2) & (exam_data1.score>15)]

name  score  attempts qualify
j  Jonas   19.0         1     yes

### 10. Write a Python program to append a new row 'k' to Data Frame with given values for each column. Now delete the new row and return the original data frame.


In [15]:
exam_data1.loc['k']=['Rajnikant',20,1,'yes']
exam_data1

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k  Rajnikant   20.0         1     yes

In [16]:
exam_data1=exam_data1.drop('k')

### 11. Write a Python program to sort the data frame first by 'name' in descending order, then by 'score' in ascending order.

In [17]:
exam_data1.sort_values(by=['name','score'], ascending=[False,True])

name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

### 12. Write a Python program to insert a new column in existing DataFrame.

In [18]:
exam_data1['new_col']=10

In [19]:
exam_data1

name  score  attempts qualify  new_col
a  Anastasia   12.5         1     yes       10
b       Dima    9.0         3      no       10
c  Katherine   16.5         2     yes       10
d      James    NaN         3      no       10
e      Emily    9.0         2      no       10
f    Michael   20.0         3     yes       10
g    Matthew   14.5         1     yes       10
h      Laura    NaN         1      no       10
i      Kevin    8.0         2      no       10
j      Jonas   19.0         1     yes       10

### 13. Write a Python program to change the name 'James' to 'Suresh' in name column of the data frame.

In [20]:
exam_data1['name'].replace('James','Suresh')

a    Anastasia
b         Dima
c    Katherine
d       Suresh
e        Emily
f      Michael
g      Matthew
h        Laura
i        Kevin
j        Jonas
Name: name, dtype: object

### 14. If column source_id has prefix “ch”  then add columns gross and amount values else subtract column amount value from column gross value


In [6]:
import pandas as pd
df=pd.read_csv('question14.csv')
df.head()

source_id   gross  amount
0  ch_1ImGtQH0noKNrKukNkUoH6No  993.04  993.04
1  ch_1ImHUfH0noKNrKukhEjgQ5hI  195.04  195.04
2  ch_1ImIQRH0noKNrKukF3vt8Kyo   87.10   87.10
3  ch_1ImIYmH0noKNrKuk2ieQ0hsW  309.07  309.07
4  re_1ImIfSH0noKNrKuk9yYipe8Y  -50.00  -50.00

In [11]:
# if df['source_id'][0][0:2]=='ch':
#     df['Operation']=df['gross']+df['amount']
# else:
#     df['Operation']=df['gross']-df['amount']
# df
df['source_id'][0]

're_1ImIfSH0noKNrKuk9yYipe8Y'